CONTAINER O_AMa_ChamferMaker
{
NAME O_AMa_ChamferMaker;
INCLUDE Obase;
GROUP ID_OBJECTPROPERTIES
{
	GROUP
	{
		COLUMNS 2;
		BOOL AMa_CHMMKR_ALL_CHILDREN {}
		BOOL AMa_CHMMKR_HN_RESET {}
	}
	GROUP
	{
		COLUMNS 2;
		LONG AMa_CHMMKR_SEL_MODE
		{
			CYCLE
			{
				AMa_CHMMKR_SELMO_LIVE;
				AMa_CHMMKR_SELMO_NSSET;
				AMa_CHMMKR_SELMO_CHOOSE;
				AMa_CHMMKR_SELMO_OPEN;
				AMa_CHMMKR_SELMO_PHO;
				AMa_CHMMKR_SELMO_THRESH;
				AMa_CHMMKR_SELMO_ALL;
			}
		}
		STATICTEXT {}
	}
	LONG AMa_CHMMKR_N_TH_SS { MIN 1; MAX 180; }
	GROUP
	{
		COLUMNS 2;
		REAL AMa_CHMMKR_SELECT_THRESH { MIN 0; MAX 180; }
		BOOL AMa_CHMMKR_AND_OPEN_EDG {}
	}
	IN_EXCLUDE AMa_CHMMKR_IN_EXCL { NUM_FLAGS 0; ACCEPT { Tedgeselection; } }
	SEPARATOR { LINE; }
	GROUP
	{
		COLUMNS 2;
		LONG AMa_CHMMKR_SHAPE_MODE
		{
			CYCLE
			{
				AMa_CHMMKR_MODE_LINEAR;				
				AMa_CHMMKR_MODE_CONVEX;
				AMa_CHMMKR_MODE_CONCAVE;
				AMa_CHMMKR_MODE_BEZIER;
				AMa_CHMMKR_MODE_USER;
				AMa_CHMMKR_MODE_AMaPARAL;
				AMa_CHMMKR_MODE_COMPO;
			}
		}
		STATICTEXT {}
	}	
	SEPARATOR { LINE; }
	GROUP AMa_CHMMKR_GROUP_PARALL
	{
		GROUP
		{
			COLUMNS 2;
			REAL AMa_CHMMKR_RAD_p { MIN 0.0; }
			REAL AMa_CHMMKR_RAD_PERC { UNIT PERCENT; MIN 100; }
			BOOL AMa_CHMMKR_WELD {}
			BOOL AMa_CHMMKR_CLOSE_FANS {}
			BOOL AMa_CHMMKR_PROL_OUTL {}
			BOOL AMa_CHMMKR_CONNECT_OUTL {}
			REAL AMa_CHMMKR_CONN_THRESH { MIN 0; MAX 15; STEP 0.1; }
		}
		SEPARATOR { LINE; }
		LONG AMa_CHMMKR_HN_WHAT
		{
			CYCLE
			{
				AMa_CHMMKR_HN_OFF;
				AMa_CHMMKR_HN_BOTH;
				AMa_CHMMKR_HN_E_ONLY;				
				AMa_CHMMKR_HN_P_ONLY;
			}
		}
		LONG AMa_CHMMKR_HN_PRIORITY
		{
			CYCLE
			{
				AMa_CHMMKR_HN_BIG;				
				AMa_CHMMKR_HN_LOW;
			}
		}
	}
	GROUP AMa_CHMMKR_GROUP_COMP
	{
		SEPARATOR { LINE; }
		LONG AMa_CHMMKR_COMP_SEC_MO
		{
			CYCLE
			{
				AMa_CHMMKR_MODE_LINEAR;				
				AMa_CHMMKR_MODE_CONVEX;
				AMa_CHMMKR_MODE_CONCAVE;
				AMa_CHMMKR_MODE_BEZIER;
				AMa_CHMMKR_MODE_USER;
				AMa_CHMMKR_MODE_AMaPARAL;
			}
		}
		GROUP AMa_CHMMKR_GROUP_DBL_P
		{
			COLUMNS 2;
			REAL AMa_CHMMKR_RAD_c { MIN 0.0; }
			STATICTEXT {}
			BOOL AMa_CHMMKR_COMP_CLO_F {}
			BOOL AMa_CHMMKR_COMP_PR_O {}
			BOOL AMa_CHMMKR_COMP_CONN {}
			REAL AMa_CHMMKR_COMP_CO_THR { MIN 0; MAX 15; STEP 0.1; }
		}
	}
	GROUP AMa_CHMMKR_GROUP_STANDARD
	{
		GROUP
		{
			COLUMNS 2;
			REAL AMa_CHMMKR_RAD_a	   { MIN 0.0; }
			REAL AMa_CHMMKR_VARIANCE { UNIT PERCENT; MIN 0; MAX 200; }
			LONG AMa_CHMMKR_SUBDIVISION { MIN 0; }
			BOOL AMa_CHMMKR_CREATENGONS {}
		}
		GROUP AMa_CHMMKR_GROUP_USER
		{
			SPLINE AMa_CHMMKR_PATH { SHOWGRID_H; SHOWGRID_V; GRIDSIZE_H 8; GRIDSIZE_V 8;
					EDIT_H; EDIT_V; MINSIZE_H 120; MINSIZE_V 115; HAS_PRESET_BTN; HAS_ROUND_SLIDER;
					Y_MIN_TEXT AMa_CHMMKR_PATH_Y_MIN_TXT;
					Y_MAX_TEXT AMa_CHMMKR_PATH_Y_MAX_TXT; }
			GROUP
			{
				COLUMNS 2;
				REAL AMa_CHMMKR_EXTRUSION { UNIT METER; }
				REAL AMa_CHMMKR_EXTRU_VARI { UNIT PERCENT; MIN 0; MAX 200; }
			}
		}
	}
}
}